### ISSUE TITLE
This is awesome ... We need a discussions TAB!!!

### ISSUE THREAD

**Issue by omegaui** [fruiframework/frui#2]
Hey there!
This is really an awesome project,
I got amazed by seeing the code design language that you guys are using is identical to **flutter** which is amazing, and seeing it running in rust would be more amazing.

I suggest to create a discussions page for this project.

**Comment by toiglak** [comment]
Added! Also checkout the [discord server](https://discord.gg/rqCd6Hr9)!

<a href="https://discord.gg/rqCd6Hr9"><img src="https://img.shields.io/badge/Frui-flat.svg?label=Discord&logo=discord&logoColor=ffffff&color=7389D8&labelColor=6A7EC2" alt="Discord"/></a>
